DEFAULT_FOLDER = crkbd/r2g

DEFERRED_EXEC_ENABLE = yes

CONSOLE_ENABLE = no
COMMAND_ENABLE = yes

EXTRAFLAGS += -flto
BACKLIGHT_ENABLE = no
RGBLIGHT_ENABLE = no
RGB_MATRIX_ENABLE = no
NO_USB_STARTUP_CHECK = no
BOOTMAGIC_ENBALE = yes

BLUETOOTH = AdafruitBLE
SLEEP_LED_ENABLE = no